FROM ubuntu:22.04

# 设置工作目录
WORKDIR /app

# 安装基础工具
RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirrors.aliyun.com/ubuntu|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com/ubuntu|http://mirrors.aliyun.com/ubuntu|g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# 创建非 root 用户
RUN addgroup --system --gid 1000 appuser \
    && adduser --system --uid 1000 --gid 1000 appuser \
    && mkdir -p /home/appuser \
    && chown -R appuser:appuser /app /home/appuser

# 切换为 appuser
USER appuser
WORKDIR /app

# 设置 HOME 环境变量
ENV HOME=/home/appuser

ENV GIT_ASKPASS=echo

# 保存git凭证，配置 git 用户名和邮箱，并克隆仓库
RUN git config --global credential.helper store && \
    echo "http://junerver%40qq.com:tKKBSQCRsvSd3Sh@192.168.187.232:28088" >> ~/.git-credentials && \
    echo "http://houwenjun:%40Aa123456@192.168.187.209:22999" >> ~/.git-credentials && \
    git config --global user.name "assemble_bot" && \
    git config --global user.email "assemble_bot@jkr.com" && \
    git clone "http://192.168.187.232:28088/rdcenter/app-distribution.git" /app/distribution && \
    git clone "http://192.168.187.209:22999/r/jkr/uni-base.git" /app/uni-base 

# 创建卷挂载点
VOLUME ["/app/distribution", "/app/uni-base"]

# 保持容器运行
CMD ["tail", "-f", "/dev/null"] 